=== mikethemage/BESM3CA/BESM3CA.Data/Datafiles/datafile-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for my JSON file format",

  "type": "object",

  "required": [
    "AttributeList",
    "VariantList",
    "TypeList",
    "TemplateName"
  ],

  "properties": {
    "AttributeList": {
      "$id": "#/properties/AttributeList",
      "type": "array",
      "title": "The AttributeList schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],

      "additionalItems": true,
      "items": {
        "$id": "#/properties/AttributeList/items",
        "anyOf": [
          {
            "$id": "#/properties/AttributeList/items/anyOf/0",
            "type": "object",
            "title": "The first anyOf schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},

            "required": [
              "ID",
              "Name",
              "CostperLevelDesc",
              "Progression",
              "MaxLevel",
              "Stat",
              "Page",
              "Human",
              "Type",
              "Container",
              "CostperLevel",
              "RequiresVariant",
              "SpecialPointsPerLevel",
              "SpecialContainer",
              "EnforceMaxLevel",
              "Description",
              "ChildrenList"
            ],
            "properties": {
              "ID": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/ID",
                "type": "integer",
                "title": "The ID schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0

              },
              "Name": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/Name",
                "type": "string",
                "title": "The Name schema",
                "description": "An explanation about the purpose of this instance.",
                "default": ""

              },
              "CostperLevelDesc": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/CostperLevelDesc",
                "type": "string",
                "title": "The CostperLevelDesc schema",
                "description": "An explanation about the purpose of this instance.",
                "default": ""

              },
              "Progression": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/Progression",
                "type": "string",
                "title": "The Progression schema",
                "description": "An explanation about the purpose of this instance.",
                "default": ""

              },
              "MaxLevel": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/MaxLevel",
                "type": "integer",
                "title": "The MaxLevel schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0

              },
              "Stat": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/Stat",
                "type": "string",
                "title": "The Stat schema",
                "description": "An explanation about the purpose of this instance.",
                "default": ""

              },
              "Page": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/Page",
                "type": "string",
                "title": "The Page schema",
                "description": "An explanation about the purpose of this instance.",
                "default": ""

              },
              "Human": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/Human",
                "type": "boolean",
                "title": "The Human schema",
                "description": "An explanation about the purpose of this instance.",
                "default": false

              },
              "Type": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/Type",
                "type": "string",
                "title": "The Type schema",
                "description": "An explanation about the purpose of this instance.",
                "default": ""

              },
              "Container": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/Container",
                "type": "boolean",
                "title": "The Container schema",
                "description": "An explanation about the purpose of this instance.",
                "default": false

              },
              "CostperLevel": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/CostperLevel",
                "type": "integer",
                "title": "The CostperLevel schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0

              },
              "RequiresVariant": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/RequiresVariant",
                "type": "boolean",
                "title": "The RequiresVariant schema",
                "description": "An explanation about the purpose of this instance.",
                "default": false

              },
              "SpecialPointsPerLevel": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/SpecialPointsPerLevel",
                "type": "integer",
                "title": "The SpecialPointsPerLevel schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0

              },
              "SpecialContainer": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/SpecialContainer",
                "type": "boolean",
                "title": "The SpecialContainer schema",
                "description": "An explanation about the purpose of this instance.",
                "default": false

              },
              "EnforceMaxLevel": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/EnforceMaxLevel",
                "type": "boolean",
                "title": "The EnforceMaxLevel schema",
                "description": "An explanation about the purpose of this instance.",
                "default": false

              },
              "Description": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/Description",
                "type": "string",
                "title": "The Description schema",
                "description": "An explanation about the purpose of this instance.",
                "default": ""

              },
              "ChildrenList": {
                "$id": "#/properties/AttributeList/items/anyOf/0/properties/ChildrenList",
                "type": "string",
                "title": "The ChildrenList schema",
                "description": "An explanation about the purpose of this instance.",
                "default": ""

              }
            },
            "additionalProperties": true
          }
        ]
      }
    },
    "VariantList": {
      "$id": "#/properties/VariantList",
      "type": "array",
      "title": "The VariantList schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],

      "additionalItems": true,
      "items": {
        "$id": "#/properties/VariantList/items",
        "anyOf": [
          {
            "$id": "#/properties/VariantList/items/anyOf/0",
            "type": "object",
            "title": "The first anyOf schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},

            "required": [
              "ID",
              "Name",
              "CostperLevel",
              "AttributeID",
              "Desc",
              "DefaultVariant"
            ],
            "properties": {
              "ID": {
                "$id": "#/properties/VariantList/items/anyOf/0/properties/ID",
                "type": "integer",
                "title": "The ID schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0

              },
              "Name": {
                "$id": "#/properties/VariantList/items/anyOf/0/properties/Name",
                "type": "string",
                "title": "The Name schema",
                "description": "An explanation about the purpose of this instance.",
                "default": ""

              },
              "CostperLevel": {
                "$id": "#/properties/VariantList/items/anyOf/0/properties/CostperLevel",
                "type": "integer",
                "title": "The CostperLevel schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0

              },
              "AttributeID": {
                "$id": "#/properties/VariantList/items/anyOf/0/properties/AttributeID",
                "type": "integer",
                "title": "The AttributeID schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0

              },
              "Desc": {
                "$id": "#/properties/VariantList/items/anyOf/0/properties/Desc",
                "type": "string",
                "title": "The Desc schema",
                "description": "An explanation about the purpose of this instance.",
                "default": ""

              },
              "DefaultVariant": {
                "$id": "#/properties/VariantList/items/anyOf/0/properties/DefaultVariant",
                "type": "boolean",
                "title": "The DefaultVariant schema",
                "description": "An explanation about the purpose of this instance.",
                "default": false

              }
            },
            "additionalProperties": true
          }
        ]
      }
    },
    "TypeList": {
      "$id": "#/properties/TypeList",
      "type": "array",
      "title": "The TypeList schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],

      "additionalItems": true,
      "items": {
        "$id": "#/properties/TypeList/items",
        "anyOf": [
          {
            "$id": "#/properties/TypeList/items/anyOf/0",
            "type": "object",
            "title": "The first anyOf schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},

            "required": [
              "ID",
              "Name",
              "TypeOrder"
            ],
            "properties": {
              "ID": {
                "$id": "#/properties/TypeList/items/anyOf/0/properties/ID",
                "type": "integer",
                "title": "The ID schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0

              },
              "Name": {
                "$id": "#/properties/TypeList/items/anyOf/0/properties/Name",
                "type": "string",
                "title": "The Name schema",
                "description": "An explanation about the purpose of this instance.",
                "default": ""

              },
              "TypeOrder": {
                "$id": "#/properties/TypeList/items/anyOf/0/properties/TypeOrder",
                "type": "integer",
                "title": "The TypeOrder schema",
                "description": "An explanation about the purpose of this instance.",
                "default": 0

              }
            },
            "additionalProperties": true
          }
        ]
      }
    },
    "TemplateName": {
      "$id": "#/properties/TemplateName",
      "type": "string",
      "title": "The TemplateName schema",
      "description": "An explanation about the purpose of this instance.",
      "default": ""

    }
  }
}

=== mikethemage/BESM3CA/BESM3CA/Datafiles/BESM3E.json
{
  "AttributeList": [
    {
      "ID": 260,
      "Name": "Ageing",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 2,
      "Stat": "",
      "Page": "53",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "Missing!",
      "ChildrenList": ""
    },
    {
      "ID": 274,
      "Name": "Balance",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 1,
      "Stat": "",
      "Page": "53",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 238,
      "Name": "Blind Fighting",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 1,
      "Stat": "",
      "Page": "",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 239,
      "Name": "Blind Shooting",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 1,
      "Stat": "",
      "Page": "",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 240,
      "Name": "Brutal",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 2,
      "Stat": "",
      "Page": "",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 275,
      "Name": "Cat-Like",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 1,
      "Stat": "",
      "Page": "53",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 231,
      "Name": "Character",
      "CostperLevelDesc": "",
      "Progression": "",
      "MaxLevel": 2147483647,
      "Stat": "",
      "Page": "9",
      "Human": true,
      "Type": "Special",
      "Container": true,
      "CostperLevel": 0,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": false,
      "Description": "",
      "ChildrenList": "80,115,116,1,2,117,118,119,3,120,288,4,5,81,82,121,83,6,122,123,124,7,8,9,125,84,85,126,127,86,10,11,12,128,14,13,129,15,130,131,16,87,17,132,18,19,20,133,21,23,22,24,25,26,27,134,135,136,88,28,29,30,89,31,90,91,92,93,32,137,138,33,94,95,34,35,36,139,140,96,97,37,141,142,38,39,40,143,41,42,43,144,98,99,44,145,45,100,146,101,102,147,148,46,47,149,150,48,49,151,50,51,52,103,105,104,53,54,55,152,153,56,106,57,107,58,59,108,154,155,61,62,63,109,156,157,158,64,65,66,67,159,68,69,70,71,72,73,74,110,75,111,312,76,160,161,112,113,77,114,78,79,162,163,164"
    },
    {
      "ID": 241,
      "Name": "Concealment",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 1,
      "Stat": "",
      "Page": "",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 242,
      "Name": "Critical Strike",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 1,
      "Stat": "",
      "Page": "",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 243,
      "Name": "Dead Eye",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 1,
      "Stat": "",
      "Page": "",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 244,
      "Name": "Deflection",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 1,
      "Stat": "",
      "Page": "",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 261,
      "Name": "Disease",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 2,
      "Stat": "",
      "Page": "53",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 245,
      "Name": "Extended Range",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 1,
      "Stat": "",
      "Page": "",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 246,
      "Name": "Far Shot",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 1,
      "Stat": "",
      "Page": "",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 276,
      "Name": "Fast",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 1,
      "Stat": "",
      "Page": "53",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 262,
      "Name": "Flare Variable",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 2,
      "Stat": "",
      "Page": "53",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 263,
      "Name": "Freezing Cold",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 2,
      "Stat": "",
      "Page": "53",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 264,
      "Name": "Freezing Water",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 2,
      "Stat": "",
      "Page": "53",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 247,
      "Name": "Hardboiled",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 2147483647,
      "Stat": "",
      "Page": "",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": false,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 269,
      "Name": "High Pressure",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 2,
      "Stat": "",
      "Page": "53",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
      "Description": "",
      "ChildrenList": ""
    },
    {
      "ID": 248,
      "Name": "Judge Opponent",
      "CostperLevelDesc": "1",
      "Progression": "",
      "MaxLevel": 1,
      "Stat": "",
      "Page": "",
      "Human": false,
      "Type": "Special",
      "Container": false,
      "CostperLevel": 1,
      "RequiresVariant": false,
      "SpecialPointsPerLevel": 0,
      "SpecialContainer": false,
      "EnforceMaxLevel": true,
